name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Run Bandit (Python Security Linter)
        run: |
          pip install bandit
          bandit -r . -c .bandit -x ./venv

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker Tags and Version
        id: tags
        run: |
          if [[ "${{ github.ref }}" == refs/heads/dev ]]; then
            echo "TAGS=hardly007/password-checker-web:dev" >> $GITHUB_ENV
            echo "VERSION=dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/main ]]; then
            echo "TAGS=hardly007/password-checker-web:latest" >> $GITHUB_ENV
            echo "VERSION=main" >> $GITHUB_ENV
          else
            echo "TAGS=hardly007/password-checker-web:latest,hardly007/password-checker-web:${{ github.ref_name }}" >> $GITHUB_ENV
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.TAGS }}
          build-args: |
            APP_VERSION=${{ env.VERSION }}
