name: Build, Scan, and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Run Bandit (Python Security Linter)
        run: |
          pip install bandit
          bandit -r . -c .bandit -x ./venv

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            hardly007/password-checker-web:latest
            hardly007/password-checker-web:${{ github.ref_name }}
          build-args: |
            VERSION=${{ github.ref_name }}
